<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =  [
            [
                'name' => 'MV962 - MacBook Pro 2019 13 Inch',
                'category_id' => 1,
                'image' => 'apple1.jpg',
                'description' => 'More power. More performance.More pro',
                'price' => 1500 ,
                'color' => 'white' ,
                'weight' => '2.1kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '256 GB SSD',
                'os' => 'macOS ',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => '2013 Macbook Air ME294 15 inch',
                'category_id' => 1,
                'image' => 'apple2.jpg',
                'description' => 'the MacBook Air sits below the performance range MacBook Pro',
                'price' => 1000 ,
                'color' => 'white' ,
                'weight' => '1.9kg',
                'cpu' => 'Core i7',
                'ram' => 'RAM:4GB',
                'hdd' => '500 GB HDD',
                'os' => 'macOS',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => '2018 Macbook Pro special 15 inch',
                'category_id' => 1,
                'image' => 'apple3.jpg',
                'description' => 'the MacBook Air sits below the performance range MacBook Pro',
                'price' => 2000 ,
                'color' => 'white' ,
                'weight' => '1.7kg',
                'cpu' => 'Core i7',
                'ram' => 'RAM:8GB',
                'hdd' => '256 GB SSD',
                'os' => 'macOS',
                'card' => '',
                'quantity' => 5,
            ],
            // Category Hp
            [
                'name' => 'Laptop HP Pavilion 14-ce2041TU 6ZT94PA',
                'category_id' => 2,
                'image' => 'hp1.jpg',
                'description' => '',
                'price' => 750 ,
                'color' => 'white' ,
                'weight' => '2.0kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => 'intel hd graphics 4000',
                'quantity' => 3,
            ],
            [
                'name' => 'HP Pavilion 15-cs1004na Full-HD Laptop',
                'category_id' => 2,
                'image' => 'hp2.jpg',
                'description' => '',
                'price' => 1200 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '1 TB HDD',
                'os' => 'window 10',
                'card' => 'Radeon HD4600',
                'quantity' => 3,
            ],
            [
                'name' => 'HP Envy 13 ah0025TU',
                'category_id' => 2,
                'image' => 'hp3.jpg',
                'description' => 'See the power of elegance in motion and explore the freedom to make a serious impact. Supported by an Intel® processor, high-performance graphics',
                'price' => 1200 ,
                'color' => 'gold' ,
                'weight' => '1.5kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '128 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA® GeForce® GTX 1050',
                'quantity' => 5,
            ],
            [
                'name' => 'HP Pavilion 15-cs1504na 15.6',
                'category_id' => 2,
                'image' => 'hp4.jpg',
                'description' => 'Fast computing with the latest tech',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '2.2kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA® GeForce® GTX 1050',
                'quantity' => 10,
            ],
            [
                'name' => 'HP Pavilion 15-bc400na ',
                'category_id' => 2,
                'image' => 'hp5.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potential,',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '2.1kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA® GeForce® MX110 4GB GDDR5',
                'quantity' => 7,
            ],
            [
                'name' => 'Laptop HP Pavilion X360 ',
                'category_id' => 2,
                'image' => 'hp6.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potential,',
                'price' => 500 ,
                'color' => 'sliver' ,
                'weight' => '2.1kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 7,
            ],
            [
                'name' => 'Laptop HP 15-da1031TX ',
                'category_id' => 2,
                'image' => 'hp6.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potential,',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '1.5kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA® GeForce® MX110 2GB GDDR5',
                'quantity' => 7,
            ],
            [
                'name' => 'Laptop HP Pavilion 15-cs1009TU 5JL43PA ',
                'category_id' => 2,
                'image' => 'hp6.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potential,',
                'price' => 1200 ,
                'color' => 'white' ,
                'weight' => '2.1kg',
                'cpu' => 'Intel Core i5 8265U ',
                'ram' => 'RAM:4GB DDR4',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => 'Intel UHD Graphics 6205',
                'quantity' => 2,
            ],
            // end hp
            //let dell
            [
                'name' => 'Buy Dell Inspiron 3576 Intel Core i3 7th Gen ',
                'category_id' => 3,
                'image' => 'dell1.jpg',
                'description' => '',
                'price' => 700 ,
                'color' => 'black' ,
                'weight' => '1.9kg',
                'cpu' => 'Core i3',
                'ram' => 'RAM:4GB',
                'hdd' => '1TB HDD',
                'os' => 'Windows 10 Home',
                'card' => 'Intel 2GB Graphics',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspiron 3576 Black ',
                'category_id' => 3,
                'image' => 'dell2.jpg',
                'description' => '',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '2.3kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB HDD',
                'os' => 'Windows 10 Home',
                'card' => 'Intel 4GB Graphics',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Vostro 7th Gen ',
                'category_id' => 3,
                'image' => 'dell3.jpg',
                'description' => '',
                'price' => 1200 ,
                'color' => 'black' ,
                'weight' => '1.7kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => '512 GB SSD',
                'os' => 'Ubuntu Linux',
                'card' => ' Intel HD Integrated Graphics 4GB',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Latitude 7490 ',
                'category_id' => 3,
                'image' => 'dell4.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potentialA lightweight and durable business machine,',
                'price' => 650 ,
                'color' => 'black' ,
                'weight' => '2.3kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB HDD',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Laptop Dell Latitude E5570  ',
                'category_id' => 3,
                'image' => 'dell5.jpg',
                'description' => 'Our most secure Latitude 5000 15 inch mainstream business laptop is now thinner, lighter and beautifully designed, so you can work confidently',
                'price' => 750 ,
                'color' => 'black' ,
                'weight' => '1.9kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8 GB DDR4',
                'hdd' => '512 GB HDD',
                'os' => 'window 10',
                'card' => 'Intel UHD Graphics 520',
                'quantity' => 3,
            ],
            [
                'name' => 'Laptop  Dell Precision M5510  ',
                'category_id' => 3,
                'image' => 'dell6.jpg',
                'description' => 'Dell Precision 5510 is the thinnest, lightest 15 inch workstation ever. It is fully customizable and certified to run professional applications.',
                'price' => 1500 ,
                'color' => 'sliver' ,
                'weight' => '1.4kg',
                'cpu' => 'Core i7 - 6820HQ ',
                'ram' => 'RAM:8 GB DDR4',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA Quadro M1000M – 4GB GDDR5',
                'quantity' => 3,
            ],
            [
                'name' => 'Laptop Dell XPS 9360  ',
                'category_id' => 3,
                'image' => 'dell7.jpg',
                'description' => '',
                'price' => 2000 ,
                'color' => 'sliver' ,
                'weight' => '1.2kg',
                'cpu' => 'Intel Core i7-8550U Kaby Lake ',
                'ram' => 'RAM:8 GB DDR4',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => ' Intel HD Graphics 620',
                'quantity' => 4,
            ],
            [
                'name' => 'Laptop Gaming  Dell Inspiron 5577  ',
                'category_id' => 3,
                'image' => 'dell8.jpg',
                'description' => 'Dell Inspiron 15 (5577) Gaming Usage and Troubleshooting Guide. Quick Links ... Static Noise from Speakers on Select Dell Inspiron Laptop PCs',
                'price' => 1750 ,
                'color' => 'sliver' ,
                'weight' => '1.4kg',
                'cpu' => 'Intel Core i7 3.2GHz  ',
                'ram' => 'RAM:8 GB DDR4',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => '  NVIDIA GeForce GTX 1050 4GB DDR5 ',
                'quantity' => 6,
            ],
            [
                'name' => ' Laptop Gaming Dell G3 3590 70191515  ',
                'category_id' => 3,
                'image' => 'dell9.jpg',
                'description' => '15-inch gaming laptop engineered with dynamic Game Shift technology, NVIDIA® GeForce® discrete graphics, and up to 9th Gen Intel® i7 processors.',
                'price' => 2250 ,
                'color' => 'black' ,
                'weight' => '2.4kg',
                'cpu' => 'Intel® Core™ i7-9750H  ',
                'ram' => 'RAM:16 GB DDR4',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => '  NVIDIA GeForce® GTX 1660 6GB GDDR6',
                'quantity' => 4,
            ],
            [
                'name' => 'Laptop Dell Inspiron 3480i ',
                'category_id' => 3,
                'image' => 'dell10.jpg',
                'description' => '15-inch gaming laptop engineered with dynamic Game Shift technology, NVIDIA® GeForce® discrete graphics, and up to 9th Gen Intel® i7 processors.',
                'price' => 2250 ,
                'color' => 'white' ,
                'weight' => '2.4kg',
                'cpu' => 'CPU Intel® Core™ i5-8265U Processor   ',
                'ram' => 'RAM:16 GB DDR4',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => '  NVIDIA GeForce® GTX 1660 6GB GDDR6',
                'quantity' => 4,
            ],
            [
                'name' => 'Laptop Dell Inspiron 5584Y P85F001 ',
                'category_id' => 3,
                'image' => 'dell11.jpg',
                'description' => '',
                'price' => 650 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Intel Core i7',
                'ram' => 'RAM:4 GB ',
                'hdd' => '256 GB HDD',
                'os' => 'window 10',
                'card' => '  Nvidia MX130 2Gb DDR5',
                'quantity' => 4,
            ],
            // Laptop Asus
            [
                'name' => ' Laptop Asus FX705DD AU059T',
                'category_id' => 4,
                'image' => 'asus1.jpg',
                'description' => 'Unite the latest AMD Ryzen™ processor and NVIDIA GeForce GTX™ graphics on a vibrant NanoEdge display with the new ASUS TUF Gaming FX705',
                'price' => 700 ,
                'color' => 'black' ,
                'weight' => '2.3kg',
                'cpu' => 'AMD Ryzen 7 – 3750H',
                'ram' => 'DDR4 8GB  ',
                'hdd' => '512GB SSD NVMe M.2 PCIe Gen 3 x 2',
                'os' => 'Windows 10 SL 64 Bit',
                'card' => 'Geforce GTX 1050 3GB',
                'quantity' => 4,
            ],
            [
                'name' => ' Laptop Asus Vivobook A512FA-EJ099T',
                'category_id' => 4,
                'image' => 'asus2.jpg',
                'description' => 'Unite the latest AMD Ryzen™ processor and NVIDIA GeForce GTX™ graphics on a vibrant NanoEdge display with the new ASUS TUF Gaming FX705',
                'price' => 650 ,
                'color' => 'sliver gold,blue' ,
                'weight' => '1.5kg',
                'cpu' => 'Intel Core i3 8145U',
                'ram' => ' RAM:	4GB  ',
                'hdd' => 'HDD 1000GB',
                'os' => 'Windows 10 home',
                'card' => '	Intel HD 620',
                'quantity' => 6,
            ],
            [
                'name' => ' Laptop Asus Vivobook A512FA-EJ1170T',
                'category_id' => 4,
                'image' => 'asus3.jpg',
                'description' => 'Unite the latest AMD Ryzen™ processor and NVIDIA GeForce GTX™ graphics on a vibrant NanoEdge display with the new ASUS TUF Gaming FX705',
                'price' => 800 ,
                'color' => 'white' ,
                'weight' => '1.9kg',
                'cpu' => 'Intel Core i5 ',
                'ram' => ' RAM:	8GB  ',
                'hdd' => 'SSD 256 GB',
                'os' => 'Windows 10 home',
                'card' => 'Intel HD Graphics 620',
                'quantity' => 4,
            ],
            [
                'name' => ' Laptop Asus Vivobook X507UF',
                'category_id' => 4,
                'image' => 'asus4.jpg',
                'description' => 'ASUS VivoBook 14 is the laptop that immerses you in whatever you set out to do. Its new frameless four-sided NanoEdge display',
                'price' => 670 ,
                'color' => 'white' ,
                'weight' => '1.4kg',
                'cpu' => 'Intel Core i7 ',
                'ram' => ' RAM:	4GB  ',
                'hdd' => 'SSD 512 GB',
                'os' => 'Windows 10 home SL 64',
                'card' => 'Geforce GTX 1050 3GB',
                'quantity' => 6,
            ],
            [
                'name' => ' Laptop Asus Vivobook Asus X407MA-BV169T',
                'category_id' => 4,
                'image' => 'asus5.jpg',
                'description' => 'ASUS VivoBook 14 is the laptop that immerses you in whatever you set out to do. Its new frameless four-sided NanoEdge display',
                'price' => 760 ,
                'color' => 'sliver' ,
                'weight' => '1.4kg',
                'cpu' => 'Intel Core i5 ',
                'ram' => ' RAM:8GB  ',
                'hdd' => 'SSD 256 GB',
                'os' => 'Windows 10',
                'card' => '',
                'quantity' => 4,
            ],
            [
                'name' => 'Asus ROG Mothership (GZ700)',
                'category_id' => 4,
                'image' => 'asus6.jpg',
                'description' => 'Laptops limit cooling and lock you into a fixed position that’s needlessly rigid for desktop replacements, so we’ve reimagined the form factor to raise your game',
                'price' => 3000 ,
                'color' => 'black' ,
                'weight' => '2.4kg',
                'cpu' => 'Intel Core i9-8950HK ',
                'ram' => ' RAM:32GB  ',
                'hdd' => 'SSD 1T GB',
                'os' => 'Windows 10 Ultimate',
                'card' => 'NVIDIA GeForce RTX 2080',
                'quantity' => 4,
            ],


            // Top -product
            // [
            //     'name' => 'Macbook Pro15 ',
            //     'category_id' => 7,
            //     'image' => 'top1.jpg',
            //     'description' => '',
            //     'price' => 1300 ,
            //     'color' => 'white' ,
            //     'weight' => '1.6kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:4GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'mac os',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Surface Laptop ',
            //     'category_id' => 7,
            //     'image' => 'top2.jpg',
            //     'description' => '',
            //     'price' => 1200 ,
            //     'color' => 'red' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Dell Inspirion 5570 ',
            //     'category_id' => 7,
            //     'image' => 'top3.jpg',
            //     'description' => '',
            //     'price' => 950 ,
            //     'color' => 'white' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Dell Inspirion 5570 ',
            //     'category_id' => 7,
            //     'image' => 'top3.jpg',
            //     'description' => '',
            //     'price' => 950 ,
            //     'color' => 'white' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Dell Inspirion 5570 ',
            //     'category_id' => 7,
            //     'image' => 'top3.jpg',
            //     'description' => '',
            //     'price' => 950 ,
            //     'color' => 'white' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Dell Inspirion 5570 ',
            //     'category_id' => 7,
            //     'image' => 'top3.jpg',
            //     'description' => '',
            //     'price' => 950 ,
            //     'color' => 'white' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Dell Inspirion 5570 ',
            //     'category_id' => 7,
            //     'image' => 'top3.jpg',
            //     'description' => '',
            //     'price' => 950 ,
            //     'color' => 'white' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
            // [
            //     'name' => 'Dell Inspirion 5570 ',
            //     'category_id' => 7,
            //     'image' => 'top3.jpg',
            //     'description' => '',
            //     'price' => 950 ,
            //     'color' => 'white' ,
            //     'weight' => '1.8kg',
            //     'cpu' => 'Core i5',
            //     'ram' => 'RAM:8GB',
            //     'hdd' => 'SSD 256GB',
            //     'os' => 'window 10',
            //     'card' => '',
            //     'quantity' => 3,
            // ],
        ];
        DB::table('products')->insert($data);

    }
}
