<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =  [
            [
                'name' => 'MV962 - MacBook Pro 2019 13 Inch',
                'category_id' => 1,
                'image' => 'apple1.jpg',
                'description' => 'More power. More performance.More pro',
                'price' => 1500 ,
                'color' => 'white' ,
                'weight' => '2.1kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '256 GB SSD',
                'os' => 'macOS ',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => '2013 Macbook Air ME294 15 inch',
                'category_id' => 1,
                'image' => 'apple2.jpg',
                'description' => 'the MacBook Air sits below the performance range MacBook Pro',
                'price' => 1000 ,
                'color' => 'white' ,
                'weight' => '1.9kg',
                'cpu' => 'Core i7',
                'ram' => 'RAM:4GB',
                'hdd' => '500 GB HDD',
                'os' => 'macOS',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => '2018 Macbook Pro special 15 inch',
                'category_id' => 1,
                'image' => 'apple3.jpg',
                'description' => 'the MacBook Air sits below the performance range MacBook Pro',
                'price' => 2000 ,
                'color' => 'white' ,
                'weight' => '1.7kg',
                'cpu' => 'Core i7',
                'ram' => 'RAM:8GB',
                'hdd' => '256 GB SSD',
                'os' => 'macOS',
                'card' => '',
                'quantity' => 5,
            ],
            [
                'name' => 'Laptop HP Pavilion 14-ce2041TU 6ZT94PA',
                'category_id' => 2,
                'image' => 'hp1.jpg',
                'description' => '',
                'price' => 750 ,
                'color' => 'white' ,
                'weight' => '2.0kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '256 GB SSD',
                'os' => 'window 10',
                'card' => 'intel hd graphics 4000',
                'quantity' => 3,
            ],
            [
                'name' => 'HP Pavilion 15-cs1004na Full-HD Laptop',
                'category_id' => 2,
                'image' => 'hp2.jpg',
                'description' => '',
                'price' => 1200 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '1 TB HDD',
                'os' => 'window 10',
                'card' => 'Radeon HD4600',
                'quantity' => 3,
            ],
            [
                'name' => 'HP Envy 13 ah0025TU',
                'category_id' => 2,
                'image' => 'hp3.jpg',
                'description' => 'See the power of elegance in motion and explore the freedom to make a serious impact. Supported by an Intel® processor, high-performance graphics',
                'price' => 1200 ,
                'color' => 'gold' ,
                'weight' => '1.5kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '128 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA® GeForce® GTX 1050',
                'quantity' => 5,
            ],
            [
                'name' => 'HP Pavilion 15-cs1504na 15.6',
                'category_id' => 2,
                'image' => 'hp4.jpg',
                'description' => 'Fast computing with the latest tech',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '2.2kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => 'NVIDIA® GeForce® GTX 1050',
                'quantity' => 10,
            ],
            [
                'name' => 'HP Pavilion 15-bc400na ',
                'category_id' => 2,
                'image' => 'hp5.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potential,',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '2.1kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB SSD',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 7,
            ],
            // end hp
            //let dell
            [
                'name' => 'Buy Dell Inspiron 3576 Intel Core i3 7th Gen ',
                'category_id' => 3,
                'image' => 'hp1.jpg',
                'description' => '',
                'price' => 700 ,
                'color' => 'black' ,
                'weight' => '1.9kg',
                'cpu' => 'Core i3',
                'ram' => 'RAM:4GB',
                'hdd' => '1TB HDD',
                'os' => 'Windows 10 Home',
                'card' => 'Intel 2GB Graphics',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspiron 3576 Black ',
                'category_id' => 3,
                'image' => 'hp2.jpg',
                'description' => '',
                'price' => 800 ,
                'color' => 'black' ,
                'weight' => '2.3kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB HDD',
                'os' => 'Windows 10 Home',
                'card' => 'Intel 4GB Graphics',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Vostro 7th Gen ',
                'category_id' => 3,
                'image' => 'hp3.jpg',
                'description' => '',
                'price' => 1200 ,
                'color' => 'black' ,
                'weight' => '1.7kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => '512 GB SSD',
                'os' => 'Ubuntu Linux',
                'card' => ' Intel HD Integrated Graphics 4GB',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Latitude 7490 ',
                'category_id' => 3,
                'image' => 'hp4.jpg',
                'description' => 'Power your passion Get ready to unleash your inner content-creating, media-craving, game-crushing potentialA lightweight and durable business machine,',
                'price' => 650 ,
                'color' => 'black' ,
                'weight' => '2.3kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => '512 GB HDD',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            // Top -product
            [
                'name' => 'Macbook Pro15 ',
                'category_id' => 7,
                'image' => 'top1.jpg',
                'description' => '',
                'price' => 1300 ,
                'color' => 'white' ,
                'weight' => '1.6kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:4GB',
                'hdd' => 'SSD 256GB',
                'os' => 'mac os',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Surface Laptop ',
                'category_id' => 7,
                'image' => 'top2.jpg',
                'description' => '',
                'price' => 1200 ,
                'color' => 'red' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspirion 5570 ',
                'category_id' => 7,
                'image' => 'top3.jpg',
                'description' => '',
                'price' => 950 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspirion 5570 ',
                'category_id' => 7,
                'image' => 'top3.jpg',
                'description' => '',
                'price' => 950 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspirion 5570 ',
                'category_id' => 7,
                'image' => 'top3.jpg',
                'description' => '',
                'price' => 950 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspirion 5570 ',
                'category_id' => 7,
                'image' => 'top3.jpg',
                'description' => '',
                'price' => 950 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspirion 5570 ',
                'category_id' => 7,
                'image' => 'top3.jpg',
                'description' => '',
                'price' => 950 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
            [
                'name' => 'Dell Inspirion 5570 ',
                'category_id' => 7,
                'image' => 'top3.jpg',
                'description' => '',
                'price' => 950 ,
                'color' => 'white' ,
                'weight' => '1.8kg',
                'cpu' => 'Core i5',
                'ram' => 'RAM:8GB',
                'hdd' => 'SSD 256GB',
                'os' => 'window 10',
                'card' => '',
                'quantity' => 3,
            ],
        ];
        DB::table('products')->insert($data);

    }
}
